name: Debug Build and Test

on: [push, pull_request]

jobs:
  build-release:
    runs-on: windows-latest

    env:
      #/ Skips dotnet's initial cache populating.
      #\ Since this is a CI, doing this is unnecessary.
      # (Probably not needed as we don't use actions/setup-dotnet, but it doesn't hurt.)
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - name: Checkout and Initialise
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Get Date and time
      # (Currently unused)
      - name: Set Date Output
        id: date
        shell: pwsh
        run: |
          echo "::set-output name=date-month::$(Get-Date -Format 'yyyy-MM')"
          echo "::set-output name=date-time::$(Get-Date -Format 'yyyy-MM-dd_HH-mm')"

      - name: Build release
        run: dotnet publish -c Release -p:PublishSingleFile=true --self-contained false

      # Upload build artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: DMM-singlefile-${{ github.sha }}
          path: |
            DivaModManager/bin/Release/net5.0-windows/win10-x64/publish
            !DivaModManager/bin/Release/net5.0-windows/win10-x64/publish/DivaModManager
